on:
  push

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
    
      - name: Build Go
        run: go build -v ./...
    
      - name: Test Go
        run: go test -v ./...
